---
- name: Install Apache.
  hosts: all
  become: true
  
  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - debug: var=ansible_os_family
    - name: Load variable files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yml"
        - "vars/apache_default.yml"

  tasks:
    - name: Ensure Apache is installed.
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy test config file.
      copy:
        src: ./test.conf
        dest: "{{ apache_config_dir }}/test.conf"
      notify: restart apache
    
    - name: Make sure handlers are flushed immediatly.
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot
      service:
        name: "{{ apache_service }}" 
        state: started
        enabled: true
