---
- name: Install Apache.
  hosts: centos
  become: true

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted


  tasks:
    - name: Ensure Apache is installed.
      yum:
        name: httpd
        state: present

    - name: Copy test config file.
      copy:
        src: ./test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: restart apache
    
    - name: Make sure handlers are flushed immediatly.
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot
      systemd:
        name: httpd
        state: started
        enabled: true
