---
- name: Install Apache.
  hosts: centos 
  become: true

  # vars_files:
  #   - "vars/apache_default.yml"
  #   - "vars/apache_{{ ansible_os_family }}.yml"

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service_ubuntu }}"
        state: restarted

  pre_tasks:
    - name: Load variable files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_default.yml"
        - "vars/apache_{{ ansible_os_family }}.yml"

  tasks:
    - name: Ensure Apache is installed.
      package:
        name: "{{ apache_package_ubuntu }}"
        state: present

    - name: Copy test config file.
      copy:
        src: ./test.conf
        dest: /etc/apache2/test.conf
      notify: restart apache
    
    - name: Make sure handlers are flushed immediatly.
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot
      service:
        name: "{{ apache_service_ubuntu }}" 
        state: started
        enabled: true
