---
- name: Install Apache.
  hosts: ubuntu
  become: true

  vars:
    apache_package: httpd
    apache_service: httpd
    apache_package_ubuntu: apache2
    apache_service_ubuntu: apache2

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service_ubuntu }}"
        state: restarted

  tasks:
    - name: Ensure Apache is installed.
      apt:
        name: "{{ apache_package_ubuntu }}"
        state: present

    - name: Copy test config file.
      copy:
        src: ./test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: restart apache
    
    - name: Make sure handlers are flushed immediatly.
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot
      service:
        name: "{{ apache_service_ubuntu }}" 
        state: started
        enabled: true
