---
- hosts: all
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install EPEL repo.
      yum:
        name: epel-release
        state: present

    - name: Ensure firewalld is stopped (since this is a test server).
      service:
        name: firewalld
        state: stopped

    - name: Install node.js and npm.
      package:
        name: npm
        state: present
        enablerepo: epel

    - name: Install Forever (to run our Node.js app).
      community.general.npm:
        name: forever
        # global: yes
        state: present

    - name: Ensure Node.js app folder exist.
      file:
        path: "{{ node_apps_location }}"
        state: directory

