# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/centos8"
  config.vm.hostname = "nodejs.test"
  config.vm.network "private_network", ip: "172.28.88.166"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disable: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
  end

  # Ansible provisioner.
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "main.yml"
  end
end
