# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu2004"

  config.ssh.insert_key = false
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = "1"
    vb.linked_clone = true
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.boot_timeout = 300

  # ubuntu server
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu.test"
    ubuntu.vm.network "private_network", ip: "192.168.40.2"
  end

  # ubuntu server
  config.vm.define "centos" do |centos|
    centos.vm.box = "geerlingguy/centos7"
    centos.vm.hostname = "centos.test"
    centos.vm.network "private_network", ip: "192.168.40.3"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 256
    end
  end

  # ansible runner
  config.vm.define "runner" do |runner|
    runner.vm.hostname = "runner.test"
    runner.vm.network "private_network", ip: "192.168.40.4"
    runner.vm.provision "shell", path: "bootstrap.sh"
  end
end
