# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "geerlingguy/rockylinux7"
    config.vm.hostname = "solr.test"
    config.vm.network :private_network, ip: "172.28.88.167"
    config.ssh.insert_key = false

    config.vm.provider :virtualbox do |v|
        v.memory = 256
    end

    # Ansible provisioner.
    config.vm.provision :ansible do |ansible|
        ansible.playbook = "main.yml"
    end
end
