---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    # Syntax check will pass whether or not this file exists.
    - name: Check syntax.
      ansible.builtin.include_tasks: date.yml

    # This will cause a failure, since it can be checked statically.
    # - ansible.builtin.import_tasks: free.yml

    - name: Print a debug message.
      ansible.builtin.debug:
        msg: "Hello there."
